version: '3.8'

services:
  nextjs-app:
    image: htpswebsite-nextjs # 指定构建好的镜像名
    container_name: htpswebsite-nextjs # 设置容器名称
    ports:
      - "3000:3000" # 将容器的3000端口映射到主机的3000端口
    restart: unless-stopped # 如果容器停止，自动重启
    environment:
      - NODE_ENV=production # 设置环境变量，指定生产环境
    volumes:
      - ./logs:/app/logs # 挂载本地目录到容器中（如果你需要存储日志等文件）
